### ISSUE TITLE
Warnings and errors caused by unecessary display features

### ISSUE THREAD

**Issue by rfetick** [astro-tiptop/P3#27]
Hello,

The code `P3\aoSystem\fourierModel.py` contains fancy plotting options but that cause warnings on my side and even crash of HSIM for astronomers. These options seem unecessary for Tiptop to run and could be erased. Here is a copy of the lines to be erased:

```python
#%% DISPLAY FEATURES
mpl.rcParams['font.size'] = 16

if find_executable('tex'): 
    usetex = True
else:
    usetex = False

plt.rcParams.update({
    "text.usetex": usetex,
    "font.family": "serif",
    "font.serif": ["Palatino"],
})
```

Kind regards,

Romain

**Comment by guidoagapito** [comment]
We could change these lines to:

```
if find_executable('tex'): 
    #%% DISPLAY FEATURES
    mpl.rcParams['font.size'] = 16
    usetex = True
    plt.rcParams.update({
        "text.usetex": usetex,
        "font.family": "serif",
        "font.serif": ["Palatino"],
    })
```

**Comment by guidoagapito** [comment]
I found that we can define a list of font styles for the font.family that will be tried in order:

```
plt.rcParams.update({
    "text.usetex": usetex,
    "font.family": "serif",
    "font.serif": ["Palatino","DejaVu Sans"],
})
```

**Comment by guidoagapito** [comment]
Pull request merged https://github.com/astro-tiptop/P3/pull/28
